// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR57ZmEtDmG1y14bNmEIbHW_GhFKvTkeA',
    appId: '1:886743449357:web:3a8303849a3d4005347a44',
    messagingSenderId: '886743449357',
    projectId: 'stokya-bc243',
    authDomain: 'stokya-bc243.firebaseapp.com',
    storageBucket: 'stokya-bc243.firebasestorage.app',
    measurementId: 'G-J4M12BJK32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWBheRLXOVmsaubzkc8IvxZRYovOnnDuo',
    appId: '1:886743449357:android:5340fba0278c9c91347a44',
    messagingSenderId: '886743449357',
    projectId: 'stokya-bc243',
    storageBucket: 'stokya-bc243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_kX1oxyKvo5gJj6VJ8pBCWQQrcwIIY0',
    appId: '1:886743449357:ios:ab276ac28923a8f7347a44',
    messagingSenderId: '886743449357',
    projectId: 'stokya-bc243',
    storageBucket: 'stokya-bc243.firebasestorage.app',
    iosBundleId: 'com.example.stokya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_kX1oxyKvo5gJj6VJ8pBCWQQrcwIIY0',
    appId: '1:886743449357:ios:ab276ac28923a8f7347a44',
    messagingSenderId: '886743449357',
    projectId: 'stokya-bc243',
    storageBucket: 'stokya-bc243.firebasestorage.app',
    iosBundleId: 'com.example.stokya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR57ZmEtDmG1y14bNmEIbHW_GhFKvTkeA',
    appId: '1:886743449357:web:b3b64b913d50814b347a44',
    messagingSenderId: '886743449357',
    projectId: 'stokya-bc243',
    authDomain: 'stokya-bc243.firebaseapp.com',
    storageBucket: 'stokya-bc243.firebasestorage.app',
    measurementId: 'G-M1NY2M4Z2S',
  );
}
